<a href="https://colab.research.google.com/github/sadman59m/My-ML/blob/main/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libraries

In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [19]:
dataset = pd.read_csv('Data.csv')
# X is the independent or featuer , Y is the dependent variable
# in the X, the the firest 3 cols with all rows
X = dataset.iloc[:, :-1].values
# Y the last col with all rows
Y = dataset.iloc[:, -1].values

In [20]:
n_cols = []
for index, x in enumerate(X[0]):
  if type(x) == float or type(x) == int:
    n_cols.append(index)
numeric_x = X[:, n_cols]
print(numeric_x)

[[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [40.0 nan]
 [35.0 58000.0]
 [nan 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]]


# Handling Missing Values
Generally we replace the missing values with average of all values. We do this in numerical columns

In [21]:
# use scikit learn to perform it
from sklearn.impute import SimpleImputer
# np.nan means the numpy nun values
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# pass all the cols of X with numerical values
# in X, 2nd and 3rd cols with all the rows
imputer.fit(X[:, 1:3])
# replace the X with new transformed X cols. The values are replaced with average
X[: , 1:3] = imputer.transform(X[:, 1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# Encoding Categorycal Data
Means representing the Text Data colums with numeircal Data.

Encoding Indepent Variable \
here, France, Spain, Gernamy\
Values are assigned as 0.0 0.1 1.0 to prevent squilization of 0, 1, 2 which will mislead the model

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# transformers is an array, where the last arg is the column to encode. [0] means 1st one
# passthrough is used to keep all the other columns
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

# make the transformed array as numpy array, which is expected by ML models
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Encoding Dependent Variable, yes and no to 1 and 0



In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)
print(Y)

[0 1 0 0 1 1 0 1 0 1]


# Dataset Splitting
- Apply Feature Scaling After Splitting the Data into training and test set.

- Test set is supposed to be new
- To prevent information Leaking


In [24]:
from sklearn.model_selection import train_test_split
# random state = 1 to set the same random factors for all
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

In [25]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


Feature Scaling
- To prevent the domination of one feature over another
- Feature Scaling is applied for some ML models, not all.

Generally Two technique is user for feature scaling
- Standardisation. vlaues [-3 to +3]
- Normalization. values [0 to 1]

Standardisation works for all models, but normalizaton is good for only certain models/cases. So when we are not use, better to use Standardisation.

- Only apply Feature scaling to the numerical variables
- Avoid applying in dummy variables,in this case, the <b> Encoded Category </b>

In [26]:
# apply Standardization using Scikit-learn
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
# first 2 index are the encoded values for Countries(category). so, exclude them
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
# use only transform method to avoid getting a new scaler for X_test
# this way it will apply the same transformer that was used to the training data
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [27]:
print(X_train)
print(X_test)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]
[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
